import React from 'react'
import { getPayload } from 'payload'
import configPromise from '@payload-config'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { FileText, Activity, AlertCircle, HardDrive } from 'lucide-react'
import Link from 'next/link'

export const dynamic = 'force-dynamic' // Ensure dashboard always fetches fresh data

export default async function DashboardPage() {
  const payload = await getPayload({ config: configPromise })

  // Fetch metrics in parallel for speed
  const [rawInputs, sops, categories] = await Promise.all([
    payload.find({ collection: 'raw-inputs', limit: 5, sort: '-createdAt' }),
    payload.find({ collection: 'sops', limit: 10, sort: '-createdAt' }),
    payload.find({ collection: 'categories', limit: 10 }),
  ])

  return (
    <div className="min-h-screen p-6 md:p-12 max-w-7xl mx-auto space-y-8">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-4xl font-bold tracking-tight">LogiSense Overview</h1>
          <p className="text-muted-foreground mt-1">DHL Operations Knowledge Base & AI Ingestion</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline">View Analytics</Button>
          <Button>Process New Manual Input</Button>
        </div>
      </div>

      {/* Metrics Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Pending Processing</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{rawInputs.totalDocs}</div>
            <p className="text-xs text-muted-foreground">Raw inputs from UiPath</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Active SOPs</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{sops.totalDocs}</div>
            <p className="text-xs text-muted-foreground">Generated by LogiSense AI</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Knowledge Categories</CardTitle>
            <HardDrive className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{categories.totalDocs}</div>
            <p className="text-xs text-muted-foreground">Detected SWCs</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">System Status</CardTitle>
            <AlertCircle className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">Online</div>
            <p className="text-xs text-muted-foreground">UiPath Webhook Active</p>
          </CardContent>
        </Card>
      </div>

      {/* Recent SOPs Table */}
      <Card>
        <CardHeader>
          <CardTitle>Recently Generated SOPs</CardTitle>
          <CardDescription>Documents automatically formatted by Gemini AI.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Document Title</TableHead>
                <TableHead>Date Created</TableHead>
                <TableHead className="text-right">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {sops.docs.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={3} className="text-center py-6 text-muted-foreground">
                    No SOPs generated yet. Send data via UiPath to populate.
                  </TableCell>
                </TableRow>
              ) : (
                sops.docs.map((sop) => (
                  <TableRow key={sop.id}>
                    <TableCell className="font-medium">{sop.title}</TableCell>
                    <TableCell>{new Date(sop.createdAt).toLocaleDateString()}</TableCell>
                    <TableCell className="text-right">
                      {/* We will build this TipTap editor page next */}
                      <Link href={`/dashboard/sop/${sop.id}`}>
                        <Button variant="secondary" size="sm">
                          Review & Edit
                        </Button>
                      </Link>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
